### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by darianjug** [girishso/autosleep#1]
Please add a licensing details for this project.

**Comment by girishso** [comment]
Will do. Just wondering why?

**Comment by darianjug** [comment]
Would like to contribute, so it works on the latest version. Need this on one of my projects.

**Comment by Blafy** [comment]
Hi, there is still no license, by default this does not allow others users to fork or contribute your code. Would you like to add one ?

**Comment by girishso** [comment]
Fixed. Finally!

https://github.com/girishso/autosleep/blob/master/LICENSE.md
